name: bricks

repository: https://github.com/askman-dev/bricks

packages:
  - apps/**
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: dart analyze
    exec:
      concurrency: 4

  test:dart:
    run: dart test
    description: Run tests for non-Flutter packages
    packageFilters:
      flutter: false
      dirExists: test
    exec:
      concurrency: 4

  test:flutter:
    run: flutter test
    description: Run tests for Flutter packages
    packageFilters:
      flutter: true
      dirExists: test
    exec:
      concurrency: 4

  test:
    run: |
      melos test:dart "$@"
      melos test:flutter "$@"
    description: Run all tests (both Dart and Flutter)

  format:
    run: dart format .
    exec:
      concurrency: 4

  clean:
    run: |
      melos exec -- \
        "rm -rf build .dart_tool pubspec_overrides.yaml"
